{
 "title": "OASIS: Monitoring",
 "description": "Oasis Node: Monitoring & Alerts for using prometheus and node_exporter.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Blocks Signed 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_validator_last_signed_height{job=~\".*oasis.*\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Missed Blocks [6-24h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_validator_missed_blocks{job=~\".*oasis.*\"}[24h]))",
     "legendFormat": "{{host}}-24h"
    }
   ]
  },
  {
   "title": "Signed Blocks [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "60*(rate(oasis_consensus_signed_blocks[1m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "N Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=~\".*oasis.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{job=~\".*oasis.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(tendermint_consensus_validator_power{job=~\".*oasis.*\"})/10000000000000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (host) (irate(node_cpu_seconds_total{mode=\"idle\", job=~\".*oasis.*\"}[5m])) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_free_bytes{job=~\".*oasis.*\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=~\".*oasis.*\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{job=~\".*oasis.*\"} - node_memory_MemFree_bytes{job=~\".*oasis.*\"} - node_memory_Buffers_bytes{job=~\".*oasis.*\"} - node_memory_Cached_bytes{job=~\".*oasis.*\"}) / node_memory_MemTotal_bytes{job=~\".*oasis.*\"} ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Predicted Available Gb in 7 days",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_avail_bytes{job=~\".*oasis.*\",fstype=~\"ext4|xfs\"}[24h],7*24*3600)/1024/1024/1024",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}